apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-redmine-ish
spec:
  destination:
    namespace: go-redmine-ish
    server: https://kubernetes.default.svc
  source:
    path: k8s
    repoURL: https://github.com/rpuchadm/go-redmine-ish.git
    targetRevision: HEAD
  sources: []
  project: default