---
kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-config
  namespace: go-redmine-ish
data:
  POSTGRES_DB: mydatabase
  POSTGRES_PASSWORD: password  # este campo debería estar en un secret
  POSTGRES_SERVICE: postgresql
  POSTGRES_USER: user
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: go-redmine-ish
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: go-redmine-ish-postgresql-pv  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: go-redmine-ish
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config   # Referencia al ConfigMap creado
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: go-redmine-ish
spec:
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
