apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: go-redmine-ish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD  # Variable de entorno para la contraseña
          valueFrom:
            secretKeyRef:
              name: redis-secret  # Nombre del Secret
              key: REDIS_PASSWORD # Clave en el Secret
        args: ["--requirepass", "$(REDIS_PASSWORD)"]  # Usar la contraseña en Redis        
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: go-redmine-ish
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
